# configs/base.yaml

experiment_name: "baseline_custom_cnn"

paths:
  csv_path: "data/processed/synthetic_halos.csv"   # update  path
  images_root: "data/processed/fits_images"        # root  relative_path

data:
  split_column: "split"
  train_split_value: "train"
  val_split_value: "validation"
  image_key: "relative_path"   # or "path" depending on your csv
  distance_column: "dist_int"  # or "distance"
  nh_unif_column: "nh_unif_idx"
  num_distance_bins: 4         # update   binning
  num_nh_classes: 4            # update   labels
  image_size: 96               # resize/crop target 

training:
  batch_size: 64
  num_workers: 4
  num_epochs: 20
  learning_rate: 1e-3
  weight_decay: 1e-4
  device: "cuda"   # "cpu" or "cuda"
